host: codespaces-c89ec1
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                        count
-----------------------  -------
all                            1
run_Fedup_HefQuin_query        3
total                          4

Select jobs to execute...
Execute 1 jobs...

[Wed Mar 26 13:59:38 2025]
localrule run_Fedup_HefQuin_query:
    input: /workspaces/P-TER/virtuoso-opensource-7.2.7, /workspaces/P-TER/virtuoso-opensource-7.2.7/var/lib/virtuoso/db/fedup.ini, /workspaces/P-TER/fedup-queries/q05a.sparql
    output: output/rdfs/FedUp-HefQuin/q05a.1.csv, output/rdfs/FedUp-HefQuin/q05a.1.json, output/rdfs/FedUp-HefQuin/q05a.1.txt
    jobid: 1
    reason: Missing output files: output/rdfs/FedUp-HefQuin/q05a.1.csv
    wildcards: workload=rdfs, query=q05a, run=1
    priority: 50
    resources: tmpdir=/tmp

Terminating processes on user request, this might take some time.
Traceback (most recent call last):

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 232, in spawn_job
    subprocess.check_call(cmd, shell=True)

  File "/usr/local/python/3.12.1/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'cd /workspaces/P-TER && /usr/local/python/3.12.1/bin/python3 -m snakemake --snakefile '/workspaces/P-TER/Snakefile' --target-jobs 'run_Fedup_HefQuin_query:workload=rdfs,query=q05a,run=1' --allowed-rules run_Fedup_HefQuin_query --cores 1 --attempt 1 --force-use-threads  --force --target-files-omit-workdir-adjustment --keep-storage-local-copies --max-inventory-time 0 --nocolor --notemp --no-hooks --nolock --ignore-incomplete --rerun-triggers code mtime params input software-env --conda-frontend 'conda' --shared-fs-usage sources storage-local-copies software-deployment input-output source-cache persistence --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --latency-wait 5 --scheduler 'greedy' --local-storage-prefix .snakemake/storage --scheduler-solver-path '/usr/local/python/3.12.1/bin' --default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI= --quiet progress rules --mode 'subprocess' --local-groupid 'local'' died with <Signals.SIGINT: 2>.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/python/3.12.1/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 234, in spawn_job
    raise SpawnedJobError()

snakemake.exceptions.SpawnedJobError

[Wed Mar 26 13:59:44 2025]
Error in rule run_Fedup_HefQuin_query:
    jobid: 1
    input: /workspaces/P-TER/virtuoso-opensource-7.2.7, /workspaces/P-TER/virtuoso-opensource-7.2.7/var/lib/virtuoso/db/fedup.ini, /workspaces/P-TER/fedup-queries/q05a.sparql
    output: output/rdfs/FedUp-HefQuin/q05a.1.csv, output/rdfs/FedUp-HefQuin/q05a.1.json, output/rdfs/FedUp-HefQuin/q05a.1.txt

Complete log: .snakemake/log/2025-03-26T135938.917085.snakemake.log
WorkflowError:
At least one job did not complete successfully.
