host: codespaces-c89ec1
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                        count
-----------------------  -------
all                            1
run_Fedup_HefQuin_query        2
total                          3

Select jobs to execute...
Execute 1 jobs...

[Thu Mar 13 21:33:08 2025]
localrule run_Fedup_HefQuin_query:
    input: /workspaces/P-TER/virtuoso-opensource-7.2.7, /workspaces/P-TER/virtuoso-opensource-7.2.7/var/lib/virtuoso/db/fedup.ini, /workspaces/P-TER/fedup-queries/q04h.sparql
    output: output/rdfs/FedUp-HefQuin/q04h.3.csv, output/rdfs/FedUp-HefQuin/q04h.3.json
    jobid: 3
    reason: Missing output files: output/rdfs/FedUp-HefQuin/q04h.3.csv
    wildcards: workload=rdfs, query=q04h, run=3
    priority: 50
    resources: tmpdir=/tmp

[Thu Mar 13 21:33:20 2025]
Finished job 3.
1 of 3 steps (33%) done
Select jobs to execute...
Execute 1 jobs...

[Thu Mar 13 21:33:20 2025]
localrule run_Fedup_HefQuin_query:
    input: /workspaces/P-TER/virtuoso-opensource-7.2.7, /workspaces/P-TER/virtuoso-opensource-7.2.7/var/lib/virtuoso/db/fedup.ini, /workspaces/P-TER/fedup-queries/q04h.sparql
    output: output/rdfs/FedUp-HefQuin/q04h.2.csv, output/rdfs/FedUp-HefQuin/q04h.2.json
    jobid: 2
    reason: Missing output files: output/rdfs/FedUp-HefQuin/q04h.2.csv
    wildcards: workload=rdfs, query=q04h, run=2
    priority: 50
    resources: tmpdir=/tmp

Terminating processes on user request, this might take some time.
Traceback (most recent call last):

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 232, in spawn_job
    subprocess.check_call(cmd, shell=True)

  File "/usr/local/python/3.12.1/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'cd /workspaces/P-TER && /usr/local/python/3.12.1/bin/python3 -m snakemake --snakefile '/workspaces/P-TER/Snakefile' --target-jobs 'run_Fedup_HefQuin_query:workload=rdfs,query=q04h,run=2' --allowed-rules run_Fedup_HefQuin_query --cores 1 --attempt 1 --force-use-threads  --force --target-files-omit-workdir-adjustment --keep-storage-local-copies --max-inventory-time 0 --nocolor --notemp --no-hooks --nolock --ignore-incomplete --rerun-triggers input params code mtime software-env --conda-frontend 'conda' --shared-fs-usage persistence storage-local-copies sources input-output source-cache software-deployment --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --latency-wait 5 --scheduler 'greedy' --local-storage-prefix .snakemake/storage --scheduler-solver-path '/usr/local/python/3.12.1/bin' --default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI= --quiet progress rules --mode 'subprocess' --local-groupid 'local'' died with <Signals.SIGINT: 2>.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/python/3.12.1/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 234, in spawn_job
    raise SpawnedJobError()

snakemake.exceptions.SpawnedJobError

[Thu Mar 13 21:33:22 2025]
Error in rule run_Fedup_HefQuin_query:
    jobid: 2
    input: /workspaces/P-TER/virtuoso-opensource-7.2.7, /workspaces/P-TER/virtuoso-opensource-7.2.7/var/lib/virtuoso/db/fedup.ini, /workspaces/P-TER/fedup-queries/q04h.sparql
    output: output/rdfs/FedUp-HefQuin/q04h.2.csv, output/rdfs/FedUp-HefQuin/q04h.2.json

Complete log: .snakemake/log/2025-03-13T213308.506238.snakemake.log
WorkflowError:
At least one job did not complete successfully.
