host: codespaces-c89ec1
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                        count
-----------------------  -------
all                            1
run_Fedup_FedX_query         360
run_Fedup_HefQuin_query      360
run_Fedup_Jena_query         360
run_fedX_query               360
run_hefquin_query            360
run_jena_query               360
total                       2161

Select jobs to execute...
Execute 1 jobs...

[Fri Mar 28 09:25:24 2025]
localrule run_fedX_query:
    input: /workspaces/P-TER/virtuoso-opensource-7.2.7, /workspaces/P-TER/virtuoso-opensource-7.2.7/var/lib/virtuoso/db/fedup.ini, /workspaces/P-TER/apache-jena-fuseki-4.9.0, queries/q07j.sparql, config/rdfs/endpoints.txt
    output: output/rdfs/FedX/q07j.1.csv, output/rdfs/FedX/q07j.1.json
    jobid: 568
    reason: Missing output files: output/rdfs/FedX/q07j.1.csv
    wildcards: workload=rdfs, query=q07j, run=1
    priority: 50
    resources: tmpdir=/tmp

Traceback (most recent call last):

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 232, in spawn_job
    subprocess.check_call(cmd, shell=True)

  File "/usr/local/python/3.12.1/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'cd /workspaces/P-TER && /usr/local/python/3.12.1/bin/python3 -m snakemake --snakefile '/workspaces/P-TER/Snakefile' --target-jobs 'run_fedX_query:workload=rdfs,query=q07j,run=1' --allowed-rules run_fedX_query --cores 1 --attempt 1 --force-use-threads  --force --target-files-omit-workdir-adjustment --keep-storage-local-copies --max-inventory-time 0 --nocolor --notemp --no-hooks --nolock --ignore-incomplete --rerun-triggers input software-env code params mtime --conda-frontend 'conda' --shared-fs-usage software-deployment source-cache sources persistence input-output storage-local-copies --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --latency-wait 5 --scheduler 'greedy' --local-storage-prefix .snakemake/storage --scheduler-solver-path '/usr/local/python/3.12.1/bin' --default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI= --quiet progress rules --mode 'subprocess' --local-groupid 'local'' returned non-zero exit status 1.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/python/3.12.1/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 234, in spawn_job
    raise SpawnedJobError()

snakemake.exceptions.SpawnedJobError

[Fri Mar 28 09:26:50 2025]
Error in rule run_fedX_query:
    jobid: 568
    input: /workspaces/P-TER/virtuoso-opensource-7.2.7, /workspaces/P-TER/virtuoso-opensource-7.2.7/var/lib/virtuoso/db/fedup.ini, /workspaces/P-TER/apache-jena-fuseki-4.9.0, queries/q07j.sparql, config/rdfs/endpoints.txt
    output: output/rdfs/FedX/q07j.1.csv, output/rdfs/FedX/q07j.1.json

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2025-03-28T092515.653310.snakemake.log
WorkflowError:
At least one job did not complete successfully.
